### ISSUE TITLE
Load Balancing Method?

### ISSUE THREAD

**Issue by JesusIslam** [apcera/gnatsd#35]
What load balancing method does gnatsd use? 

Is it a simple round-robin like zmq?

**Comment by joeblew99** [comment]
+1
back pressure semantics would be awesome BTW. I use Kafka for my stuff, but want to change to Nats. Having back pressure semantics would be enough to swap

**Comment by bjflanne** [comment]
Joe - can you please expand on the specific use case scenario you require back pressure semantics for? If you can provide specific details I'd like to take a look at how we might be able to make that work for you. If you prefer to send me an email on the specifics vs posting here, please email brian@apcera.com

Thanks - look forward to hearing from you/speaking soon.
