### ISSUE TITLE
Priority over Wildcards ?

### ISSUE THREAD

**Issue by maxired** [apcera/gnatsd#76]
Hi,

Is there any mechanism for sending a message to a node who listen specificly to a topic, but if nobody has subscribed to this specifi topic, then we will try to query subscribers with wildcard.

Bellow is desired behaviour :

```ruby
NATS.subscribe( "foo.bar.>" , :queue => 'job.workers') { |msg| puts "I do wildcard!" }
NATS.subscribe( "foo.bar.qux" , :queue => 'job.workers') { |msg| puts "I do qux!" }


NATS.request('foo.bar.qux') { |response| puts "QUX got a response: '#{response}'" }
NATS.request('foo.bar.baz') { |response| puts "BAZ got a response: '#{response}'" }

```
Desired output :
```
QUX got a response: I do qux!
BAZ got a response: I do wildcard!
```

**Comment by derekcollison** [comment]
If the wildcard matches it will be considered a valid subscriber along with the direct. There is not a mechanism to prioritize or segregate traffic between valid subscriptions.
